name: PR Checks

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  create_artifact:
    name: "Create Plugin Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "TEST: uninstall.php exists"
        run: |
          file="uninstall.php"
          if [ -f $file ]; then echo "$file exists"; echo "$file does not exist"; else exit 1; fi;