name: PR Checks

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  PHP_VERSION: 8.2
  PLUGIN_FILE: "class-wp-azure-application-insights.php"

jobs:
  create_artifact:
    name: "PR Check Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "TEST: uninstall.php exists"
        run: |
          file="uninstall.php"
          if [ -f $file ]; then echo "$file exists"; else exit 1; fi;

      - name: "Composer: Cache"
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: "Composer: Install"
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          dev: yes

      - name: Validate composer.json and composer.lock
        run: composer validate --strict