name: Create Plugin Package

on:
  push:
    branches:
      - develop
#  pull_request:
#    branches:
#      - develop

permissions:
  contents: write

env:
  PHP_VERSION: 8.2
  PLUGIN_FILE: "class-wp-azure-application-insights.php"

jobs:
  create_artifact:
    name: "Create Plugin Artifact"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          fetch-tags: true

#      - name: "Echo Statements"
#        run: |
#          echo "Latest Tag: $(git describe --tags --abbrev=0)"
#          echo "Repo Name: ${{ github.event.repository.name }}"
#          echo "Composer Name: ${{ github.repository }}";
#          echo "Repository Owner: ${{ github.repository_owner }}"
#          echo "Get Composer php value"
#          echo "Files in directory:"
#          ls -laGh
#          echo "Git Config"
#          git config -l
#
      - name: "Composer: Cache"
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: "Composer: Install"
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          dev: yes

#      - name: "Composer: Lint"
#        uses: php-actions/composer@v6
#        with:
#          command: "run-script lint"
#          php_version: 8.2

#      - name: Get Repository Owner
#        id: repo_owner
#        run: |
#          OWNER_EMAIL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/owner" | jq -r '.email')
#          echo "OWNER_EMAIL: $OWNER_EMAIL";
#          echo "repository_owner_email=$OWNER_EMAIL" >> $GITHUB_OUTPUT
#
#      - name: Print API data
#        run: |
#          echo "Repository Owner's Email: ${{ steps.repo_info.outputs.repository_owner_email }}"
#          echo "Repository Description: ${{ steps.repo_info.outputs.repository_description }}"

      - name: "Composer: Description"
        id: composer_config_description
        run: |
          PLUGIN_DESCRIPTION="$(composer config description)"
          echo "plugin_description=$PLUGIN_DESCRIPTION" >> $GITHUB_OUTPUT

      - name: "Version: Increment"
        id: version_incrementer
        uses: reecetech/version-increment@2023.9.3

      - name: "Update: Plugin Front Matter"
        run: |
          sed -i '/ * Version:/c\ * Version: ${{ steps.version_incrementer.outputs.version }}' ${{ env.PLUGIN_FILE }}
          sed -i '/ * Requires PHP:/c\ * Requires PHP: ${{ env.PHP_VERSION }}' ${{ env.PLUGIN_FILE }}
          sed -i '/ * Description:/c\ * Description: ${{ steps.composer_config_description.outputs.plugin_description }}' ${{ env.PLUGIN_FILE }}

      - name: "Update: Composer Package Version"
        run: |
          composer config version ${{ steps.version_incrementer.outputs.version }}

      - name: 'Git Add, Tag and Release'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Incrementing version number"
          tagging_message: '${{ steps.version_incrementer.outputs.version }}'
          file_pattern: '*.php composer.json'

      - uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version_incrementer.outputs.version }}"
          artifacts: |
            *
            !.git
            !.github
            !vendor
            !.gitignore
            !composer.json
            !composer.lock
            !*.md
            !DOCKER_ENV
            !Dockerfile-php-build
            !docker_tag
            !output.log